name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Clone Hugging Face Space with authentication
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "mrichardson@rocnation.com"
          git config --global user.name "MRichardson25"
          git clone https://MRichardson25:$HF_TOKEN@huggingface.co/spaces/MRichardson25/UJCTracker
          rsync -av --exclude '.git' ./ UJCTracker/
          cd UJCTracker
          git add .
          git commit -m "Update from GitHub Actions"
          git push origin main
